### ISSUE TITLE
Docker Ubuntu or Windows

### ISSUE THREAD

**Issue by amorenew** [kunfengchen/self-driving-car#2]
Hi
is there is a difference in performance if i use the docker on linux than windows or mac?
and if there is difference is it better to use ubuntu 14.04 or i can use ubuntu 16?

**Comment by kunfengchen** [comment]
I believe there are differences since Windows and Mac hosts need to run an additional VM layer to run Linux kernel and Docker Engine, which in turn run docker containers. On the other hand, Linux runs Docker Engine natively as a process, which in turn faster the Windows and Mac.

As far as using Ubuntu 14.04 or 16 for the host, I would suggest use a later version, 16, for newer kernel and better support for "older" versions.

**Comment by amorenew** [comment]
Thanks a lot 💯
